# Generated by Django 3.2.25 on 2025-05-07 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ModuleProgress',
        ),
        migrations.AddField(
            model_name='learninglog',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.trainingmodule'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
