# Generated by Django 3.2.25 on 2025-05-07 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='xp_reward',
            field=models.IntegerField(),
        ),
    ]
