# Generated by Django 3.2.25 on 2025-05-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20250506_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='confidence_level',
            field=models.FloatField(default=0.0),
        ),
    ]
